config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :posts
	resources :comments
  	resources :posts do
		resources :comments
	end

	root to: "posts#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
#    @comment = Comment.new(comment_params)
  
  @post = Post.find(params[:post_id])
  @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<p>
<strong> Posted <%= time_ago_in_words(comment.created_at) %></strong>
<br>
<%= h(comment.body) %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h3>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.text_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= j(render(@comment)) %>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h3>Editing Comment</h3>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p class="notice"><%= notice %></p>
<p class="notice"><%= alert %></p>

<h3>Comments</h3>

<table>
  <thead>
    <tr>
      <th>Post id</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post.id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p class="notice"><%= notice %></p>
<p class="notice"><%= alert %></p>
<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
      <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/posts"><strong>Blog</strong></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#"></a></li>
            <li><a href="#"></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="/users/sign_out" data-method="delete">Logout</a></li>
          <% else %>          
            <li><a href="/users/sign_in">Login</a></li>
            <li><a href="/users/sign_up">Register</a></li>
          <% end %>
          </ul>
        </div>
        </div>
        </div>
      </div>
    </nav>
  <div class="section">
  <div class="container">
  <div class="row">
  <div class="maincontent col-md-8 col-md-offset-2">
    <%= yield %>
  </div>
  </div>
  </div>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h3>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= div_for @post do %>
	<h3 style="text-align: center"><%= h(@post.title) %></h3>
	<%= simple_format h(@post.body) %>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing Post</h3>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p class="notice"><%= notice %></p>
<p class="notice"><%= alert %></p>
<h3>Posts</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>
<p class="notice"><%= alert %></p>

<%= render @post %>

<h3>Comments</h3>
<div id="comments">
	<%= render @post.comments.reverse %>
</div>

<%= form_for [@post, Comment.new], remote: true do |f| %>
	<p>
		<%= f.label :body, "New Comment" %>
		<%= f.text_area :body %>
	</p>
	<p> <%= f.submit "Add Comment", class: "btn btn-primary" %> </p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-primary' %>